# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HelloWorld' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HelloWorld
  pod 'DynamsoftCore', '3.2.11'
  pod 'DynamsoftLicense', '3.2.21'
  pod 'DynamsoftCodeParser', '2.2.11'
  pod 'DynamsoftCodeParserDedicator', '1.2.21'

end
