# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HelloWorld' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HelloWorld
  pod 'DynamsoftCore', '3.0.20'
  pod 'DynamsoftLicense', '3.0.30'
  pod 'DynamsoftCodeParser', '2.0.20'
  pod 'DynamsoftCodeParserDedicator', '1.0.10'

end
